name: eleccionesapp
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.4.6
  image_picker: ^1.0.7
  path: ^1.9.0
  sqflite: ^2.3.2
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/"
